### ISSUE TITLE
Should the weight attribute in the dog class be a double or an int?

### ISSUE THREAD

**Issue by jasonserviss** [OliviaImner/DogRegister#4]

**Comment by OliviaImner** [comment]
It should be a double because the output has a decimal format.

**Comment by jasonserviss** [comment]
The weight attribute has a decimal format NOW but does it need to have a decimal format? Or should we change weight to an int?

**Comment by OliviaImner** [comment]
All the dogs in the DogRegister class has a weight in a decimal number.   We can have an int if we change it.

**Comment by jasonserviss** [comment]
Should we change it then or not?

**Comment by OliviaImner** [comment]
We should no change it.

**Comment by jasonserviss** [comment]
Alright, then close the issue.

**Comment by jasonserviss** [comment]
To close the issue you click on the "Close and Comment" button.

**Comment by jasonserviss** [comment]
But this issue is resolved so close it
