### ISSUE TITLE
What does this mean: int size = currentRegister.size(); ? 

### ISSUE THREAD

**Issue by OliviaImner** [OliviaImner/DogRegister#8]
int size = currentRegister.size();
        if(size > 0) {
            //check if dog exists in current register
            String found = "no";
            loop1:
            for( int i=0; i < size; i++ ) {
                DogClass currentDog = currentRegister.get(i);
                String dogName = currentDog.getName();
                if(dogName.equals(toDelete)) {
                    found = "yes";
                    break loop1;
                }

**Comment by jasonserviss** [comment]
.size is a method of class ArrayList (i.e. I did not write it). You can find the documentation [here](https://www.google.se/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjnkvf7s8zJAhXGlSwKHTtSAfwQFggcMAA&url=http%3A%2F%2Fwww.tutorialspoint.com%2Fjava%2Futil%2Farraylist_size.htm&usg=AFQjCNHGJRDqfgXIs2a3jtI-1fpujiNVaw). The command _int size = currentRegister.size();_ places the amount of elements contained in the currentRegister variable in the size variable. So if the current register has 5 dogs then size = 5, if the current register has 2 dogs then size = 2, etc... Is that all you were wondering about that code?

**Comment by OliviaImner** [comment]
Ok. No, wondering about the loops also.

**Comment by jasonserviss** [comment]
Start by answering these questions then:

> 1. What are all the values that "i" will equal when the loop runs?
> 2. What gets placed in _currentDog_ when i = 0?
> 3. What does the _getName_ method do?

**Comment by OliviaImner** [comment]
1. It will loop every lap from 0 to size of the current register

**Comment by OliviaImner** [comment]
1. Fido
2. Get the name attribute from class Dog

**Comment by jasonserviss** [comment]
The answer to 2. is not totally right. If the dog with the name Fido is at currentRegister[0] then it is right. **BUT** if Fido was deleted earlier by the user, another dog will be copied from currentRegister[0] and placed in currentDog. So the answer is: "when i=0 currentDog will be the object stored at currentRegister[0]"

**Comment by jasonserviss** [comment]
Ok, some more questions then....

> 1. What is in the string variable named "_toDelete_"?
> 2. What is in the string variable named "dogName"?
> 3. In words, what does the boolean expression say in the if statement?
> 4. If when i=2 toDelete is equal to dogName, what happens when i=3?

**Comment by OliviaImner** [comment]
Thanks :+1:

**Comment by OliviaImner** [comment]
1. The name of the dog which the user has collected from the keyboard.
2. String dogName has the Dog class and gets the name of the dog class. 
3. If dogName is equal to deleteDog continue to loop 2. 
4. The dog which had the index 3 is now in index 2.

**Comment by jasonserviss** [comment]
1. is right
2. almost. dogName **is** the name of the dog in currentDog. only the name, nothing to do with the class
3. almost. If dogName is equal to deleteDog quit loop1
4. wrong. if the boolean expression becomes true at i=2, the loop quits and i never becomes 3. This means, as soon as we find the dog the user wants to delete we stop searching for the dog

> a special note: because we quit searching for the dog in the arrayList after we find it once, that means that if we have more than one dog **with the same name**, then when we try to delete that dog, the program will always delete the **first instance** of that dog. Do you understand this?

**Comment by jasonserviss** [comment]
### Do you understand all the code now?

#### If not, ask!

**Comment by OliviaImner** [comment]
Ok I understand the code now.

**Comment by jasonserviss** [comment]
Then you know what you need to do right....**?**
